### PR TITLE
Facilitate supplying  binaries on Windows

### PR DESCRIPTION
**Pull request by GregPlowman**

### CODE REVIEW

**Comment by GregPlowman** [comment]
Issue #9 

Andreas, I hope this is what you meant in your comment.
Binary `dll`s need to be uploaded to repository sub-folder `deps/TestU01/bin`
I have assumed there would be two such binary `dll`s, one each for 32-bit and 64-bit.
Is this the case?
Dummy files `libtestu01wrapper-32.dll` and ` libtestu01wrapper-64.dll` are currently in this PR.
Just need to upload actual replacements for these two files.
`build()` copies appropriate `dll` file to `deps` directory.
I think this should work.

**Comment by GregPlowman** [comment]
Not sure why travis failed. Is there a way to see a log, or see the error messages?

If it's something to do with `dll`s being directly in the repository, then can change code to download from a release instead of copying.

```
if Sys.WORD_SIZE == 32
    url = "https://github.com/andreasnoack/RNGTest.jl/releases/download/deplib-0.1/libtestu01wrapper-32.dll"
else
    url = "https://github.com/andreasnoack/RNGTest.jl/releases/download/deplib-0.1/libtestu01wrapper-64.dll"
end

download(url, "libtestu01wrapper.dll")
```

**Comment by GregPlowman** [comment]
Seems like this failed for osx, julia v0.5.0:
```
Test: RandomWalk: Test Failed
  Expression: all(hcat(RNGTest.swalk_RandomWalk1(f,1,1000000,0,30,150,150)...) .> pval)
ERROR: LoadError: LoadError: There was an error during testing
```
Could this be a genuine random test failure, rather than a build/julia failure?

I'll try to work out how to trigger another travis run.

**Comment by andreasnoack** [comment]
Sorry for never replying here. Windows is now supported.

**Pull request closed without merging**
